name: prox
description: Prox dev app
publish_to: "none"
version: 0.18.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.2
  firebase_app_check: ^0.4.1+2
  firebase_remote_config: ^6.1.1
  # Local storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0

  # Location / maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_local_notifications: ^19.4.2
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  connectivity_plus: ^6.1.4
  app_links: ^6.3.2
  local_auth: ^2.1.10

  # UI niceties (optional)
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1
  image_picker: ^1.1.1
  image_picker_for_web: ^3.1.0
  provider: ^6.1.5
  share_plus: ^10.1.4
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.0.2+1

flutter:
  uses-material-design: true
  assets:
    - img/prox-logo.svg
